apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v93bsa1ue-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v93bsa1ue-go 
  name: v93bsa1ue-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v93bsa1ue-go 
